openapi: 3.1.0
info:
  title: Kibana
  description: OpenAPI schema for Kibana APIs
  version: "1.0.2"
  license:
    name: Elastic License 2.0
    url: https://www.elastic.co/licensing/elastic-license
  contact: 
    name: Kibana Team
security:
  - basicAuth: []
  - apiKeyAuth: []
servers:
  - url: /
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'e.g. Authorization: ApiKey base64AccessApiKey'
  