[[cases-api-update]]
== Update case API
++++
<titleabbrev>Update case</titleabbrev>
++++

Updates cases.

=== Request

`PATCH <kibana host>:<port>/api/cases`

=== Request body

`cases`
(Required, array of objects) Array containing one or more case objects.
+
.Properties of `cases` objects
[%collapsible%open]
====

`connector`
(Optional, object) An object that contains the connector configuration.
+
.Properties of `connector`
[%collapsible%open]
====
`fields`::
(Required, object) An object containing the connector fields.
+
--

For {sn-itsm} connectors, refer to <<servicenow-action-configuration>>. For example:

* `urgency` (string \| null): The urgency of the incident.
* `severity` (string \| null): The severity of the incident.
* `impact` (string \| null): The impact of the incident.
* `category` (string \| null): The category of the incident.
* `subcategory` (string \| null): The subcategory of the incident.

For {sn-sir} connectors, refer to <<servicenow-sir-action-configuration>>. For example:

////
//TBD: Are these valid? They don't appear in the action docs
* `destIp` (string \| null): A comma separated list of destination IPs.
* `malwareHash` (string \| null): A comma separated list of malware hashes.
* `malwareUrl` (string \| null): A comma separated list of malware URLs.
* `sourceIp` (string \| null): A comma separated list of source IPs.
////
* `priority` (string \| null): The priority of the incident.
* `category` (string \| null): The category of the incident.
* `subcategory` (string \| null): The subcategory of the incident.

For {jira} connectors, refer to <<jira-action-configuration>>. For example:

* `issueType` (string): The issue type of the issue.
* `priority` (string \| null): The priority of the issue.
* `parent` (string \| null): The key of the parent issue (Valid when the issue type is `Sub-task`).

For {ibm-r} connectors, refer to <<resilient-action-configuration>>. For example:

* `issueTypes` (number[]): The issue types of the issue.
* `severityCode` (number): The severity code of the issue.

For {swimlane} connectors, refer to <<swimlane-action-configuration>>. For example:

* `caseId` (string \| null): The case ID.
//TBD: Is this correct or should it be comments and severity?
--

`id`::
(Required, string) The identifier for the connector. To retrieve connector IDs,
use <<cases-api-find-connectors>>).

`name`::
(Required, string) The name of the connector.

`type`::
(Required, string) The type of the connector. Valid values are: `.jira`, `.none`,
`.resilient`,`.servicenow`, `.servicenow-sir`, and `.swimlane`.
====

`description`::
(Optional, string) The updated case description.

`id`::
(Required, string) The identifier for the case.

`settings`::
(Optional, object)
An object that contains the case settings.
+
.Properties of `settings`
[%collapsible%open]
====
`syncAlerts`::
(Required, boolean) Turn on or off synching with alerts.
====

`status`::
(Optional, string) The case status. Valid values are: `closed`, `in-progress`, and `open`.

`tags`::
(Optional string array) The words and phrases that help
categorize cases.
//TBD: It can be an empty array?

`title`::
(Optional, string) A title for the case.

`version`::
(Required, string) The version of the case. To determine this value, use
<<cases-api-get-case>> or <<cases-api-find-cases>>
//TBD: Does this imply that you must provide a value higher than the existing version? i.e. you must increment the version with each update?
====

=== Response code

`200`::
   Indicates a successful call.

=== Example

Update the description, tags, and connector of case ID
`a18b38a0-71b0-11ea-a0b2-c51ea50a58e2`:

[source,sh]
--------------------------------------------------
PATCH api/cases
{
  "cases": [
    {
      "connector": {
        "id": "131d4448-abe0-4789-939d-8ef60680b498",
        "name": "My connector",
        "type": ".jira",
        "fields": {
          "issueType": "10006",
          "priority": null,
        }
      },
      "id": "a18b38a0-71b0-11ea-a0b2-c51ea50a58e2",
      "description": "James Bond clicked on a highly suspicious email
      banner advertising cheap holidays for underpaid civil servants.
      Operation bubblegum is active. Repeat - operation bubblegum is
      now active!",
      "tags": [
        "phishing",
        "social engineering",
        "bubblegum"
      ],
      "settings": {
        "syncAlerts": true
      }
      "version": "WzIzLDFd"
    }
  ]
}
--------------------------------------------------
// KIBANA

The API returns the updated case with a new `version` value. For example:

[source,json]
--------------------------------------------------
[
  {
    "id": "66b9aa00-94fa-11ea-9f74-e7e108796192",
    "version": "WzU0OCwxXQ==",
    "comments": [],
    "totalComment": 0,
    "connector": {
      "id": "131d4448-abe0-4789-939d-8ef60680b498",
      "name": "My connector",
      "type": ".jira",
      "fields": {
        "issueType": "10006",
        "priority": null,
      }
    },
    "title": "This case will self-destruct in 5 seconds",
    "description": "James Bond clicked on a highly suspicious email banner advertising cheap holidays for underpaid civil servants. Operation bubblegum is active. Repeat - operation bubblegum is now active!",
    "tags": [
      "phishing",
      "social engineering",
      "bubblegum"
    ],
    "settings": {
      "syncAlerts": true
    }
    "closed_at": null,
    "closed_by": null,
    "created_at": "2020-05-13T09:16:17.416Z",
    "created_by": {
      "email": "ahunley@imf.usa.gov",
      "full_name": "Alan Hunley",
      "username": "ahunley"
    },
    "external_service": {
      "external_title": "IS-4",
      "pushed_by": {
        "full_name": "Classified",
        "email": "classified@hms.oo.gov.uk",
        "username": "M"
      },
      "external_url": "https://hms.atlassian.net/browse/IS-4",
      "pushed_at": "2020-05-13T09:20:40.672Z",
      "connector_id": "05da469f-1fde-4058-99a3-91e4807e2de8",
      "external_id": "10003",
      "connector_name": "Jira"
    },
    "owner": "securitySolution",
    "status": "open",
    "updated_at": "2020-05-13T09:48:33.043Z",
    "updated_by": {
      "email": "classified@hms.oo.gov.uk",
      "full_name": "Classified",
      "username": "M"
    }
  }
]
--------------------------------------------------
