[[cases-api-update-connector]]
== Update case configurations API
++++
<titleabbrev>Update case configurations</titleabbrev>
++++

Updates the case closure settings for a connector.

////
//TBD: Fix links
Connectors are used to interface with external systems. You can only call this
method after you have created a connector (see <<register-connector>>). After a
connector has been created and assigned, call <<cases-actions-api-execute>> to
send cases to the external system.
////

=== Request

`PATCH <kibana host>:<port>/api/cases/configure/<configuration_id>`

=== Path parameters

`configuration_id`::
The identifier for the configuration. To retrieve the configuration IDs, use <<cases-get-connector>>.

=== Request body

`closure_type`::
(Optional, string) Determines whether a case is automatically closed when it is pushed to external systems. Valid values are:
+
--
* `close-by-pushing`: {es-sec} cases are automatically closed when they
are pushed.
* `close-by-user`: {es-sec} cases are not automatically closed.
--

`connector`::
(Required, object) An object that contains the connector configuration.
+
.Properties of `connector`
[%collapsible%open]
====
`fields`::
(Required, object) An object that contains the connector fields.
+
--
For {sn-itsm} connectors, refer to <<servicenow-action-configuration>>. For example:

* `urgency` (string \| null): The urgency of the incident.
* `severity` (string \| null): The severity of the incident.
* `impact` (string \| null): The impact of the incident.
* `category` (string \| null): The category of the incident.
* `subcategory` (string \| null): The subcategory of the incident.

For {sn-sir} connectors, refer to <<servicenow-sir-action-configuration>>. For example:

////
//TBD: Are these valid? They don't appear in the action docs
* `destIp` (string \| null): A comma separated list of destination IPs.
* `malwareHash` (string \| null): A comma separated list of malware hashes.
* `malwareUrl` (string \| null): A comma separated list of malware URLs.
* `sourceIp` (string \| null): A comma separated list of source IPs.
////
* `priority` (string \| null): The priority of the incident.
* `category` (string \| null): The category of the incident.
* `subcategory` (string \| null): The subcategory of the incident.

For {jira} connectors, refer to <<jira-action-configuration>>. For example:

* `issueType` (string): The issue type of the issue.
* `priority` (string \| null): The priority of the issue.
* `parent` (string \| null): The key of the parent issue (Valid when the issue type is `Sub-task`).

For {ibm-r} connectors, refer to <<resilient-action-configuration>>. For example:

* `issueTypes` (number[]): The issue types of the issue.
* `severityCode` (number): The severity code of the issue.

For {swimlane} connectors, refer to <<swimlane-action-configuration>>. For example:

* `caseId` (string \| null): The case ID.
//TBD: Is this correct or should it be comments and severity?
--

`id`::
(Required, string) The identifier for the connector. To retrieve connector IDs, use 
<<cases-api-find-connectors>>.

`name`::
(Required, string) The name of the connector.

`type`::
(Required, string) The type of the connector. Valid values are: `.servicenow`, `.servicenow-sir`, `.jira`, `.resilient`, `.swimlane`, and `.none`.
====

`version`::
(Required, string) The version of the connector. To retrieve the version value,
use <<cases-get-connector>>.
//TBD: Is the implication that you must increment the existing value?

NOTE: Fields can be set but are not being used by case configuration. You can set the fields of the connector at <<cases-api-create>>.

=== Response code

`200`::
   Indicates a successful call.

=== Example

Change the connector's case closure option:

[source,sh]
--------------------------------------------------
PATCH api/cases/configure/7349772f-421a-4de3-b8bb-2d9b22ccee30
{
  "connector": {
    "id": "131d4448-abe0-4789-939d-8ef60680b498",
    "name": "My connector",
    "type": ".jira",
    "fields": null,
  }
  "closure_type": "close-by-pushing",
  "version": "WzIwMiwxXQ=="
}
--------------------------------------------------
// KIBANA

The API returns the following:

[source,json]
--------------------------------------------------
{
  "connector": {
    "id": "131d4448-abe0-4789-939d-8ef60680b498",
    "name": "My connector",
    "type": ".jira",
    "fields": null,
  },
  "closure_type": "close-by-pushing",
  "created_at": "2020-03-30T13:31:38.083Z",
  "created_by": {
    "email": "admin@hms.gov.uk",
    "full_name": "Ms Admin",
    "username": "admin"
  },
  "error": null,
  "id": "7349772f-421a-4de3-b8bb-2d9b22ccee30",
  "owner": "securitySolution",
  "updated_at": "2020-03-31T06:21:35.759Z",
  "updated_by": {
    "email": "admin@hms.gov.uk",
    "full_name": "Ms Admin",
    "username": "admin"
  },
  "version": "WzIwMywxXQ=="
}
--------------------------------------------------
