[[cases-api-get-tag]]
== Get case tags API
++++
<titleabbrev>Get tags</titleabbrev>
++++

Aggregates and returns all unique tags from all cases.

=== Request

`GET <kibana host>:<port>/api/cases/tags`

`GET <kibana host>:<port>/s/<space_id>/api/cases/tags`

=== Prerequisite

////
//TBD, for example
You must have `read` privileges for the *Cases* feature in the *Management*,
*{observability}*, or *Security* section of the
<<kibana-feature-privileges,{kib} feature privileges>>, depending on the
`owner` of the cases you're seeking.
////

=== Path parameters

<space_id>::
(Optional, string) An identifier for the space. If it is not specified, the default space is used.

=== Query parameters

`owner`::
(Optional, string or array of strings)
A filter to limit the retrieved tags to a specific set of applications. Valid
values are: `cases`, `observability`, or `securitySolution`. If this
parameter is omitted, the response contains all tags that the user has access to
read.


=== Response code

`200`::
   Indicates a successful call.

=== Example

Get all tags for all cases:

[source,sh]
--------------------------------------------------
GET api/cases/tags
--------------------------------------------------
// KIBANA

The API returns the following type of information:

[source,json]
--------------------------------------------------
[
  "windows",
  "phishing",
  "social engineering",
  "bubblegum"
]
--------------------------------------------------
