[[cases-get-connector]]
== Get current connector API
++++
<titleabbrev>Get current connector</titleabbrev>
++++

Retrieves the connectors currently used in cases that the user has access to read.

=== Request

`GET <kibana host>:<port>/api/cases/configure`

`GET <kibana host>:<port>/s/<space_id>/api/cases/configure`

=== Prerequisite

////
//TBD, for example
You must have `read` privileges for the *Cases* feature in the *Management*,
*{observability}*, or *Security* section of the
<<kibana-feature-privileges,{kib} feature privileges>>, depending on the
`owner` of the cases you're seeking.
////

=== Path parameters

`<space_id>`::
(Optional, string) An identifier for the space. If it is not specified, the default space is used.

=== Query parameters

`owner`::
(Optional, string or array of strings) A filter to limit the retrieved connectors to
a specific set of applications. Valid values are: `cases`, `observability`,
and `securitySolution`. If this parameter is omitted, the response contains all
cases that the user has access to read.

=== Response code

`200`::
   Indicates a successful call.

=== Example

[source,sh]
--------------------------------------------------
GET api/cases/configure
--------------------------------------------------
// KIBANA

The API returns the following type of information:

[source,json]
--------------------------------------------------
[
  {
    "connector": {
      "id": "131d4448-abe0-4789-939d-8ef60680b498",
      "name": "Jira",
      "type": ".jira",
      "fields": null,
    },
    "closure_type": "close-by-user",
    "created_at": "2020-03-30T13:31:38.083Z",
    "created_by": {
      "email": "admin@hms.gov.uk",
      "full_name": "Mr Admin",
      "username": "admin"
    },
    "error": null,
    "id": "7349772f-421a-4de3-b8bb-2d9b22ccee30",
    "owner": "securitySolution",
    "updated_at": null,
    "updated_by": null,
    "version": "WzE3NywxXQ=="
  }
]
--------------------------------------------------
