[[cases-api-find-cases-by-alert]]
== Find cases by alert API
++++
<titleabbrev>Find cases by alert</titleabbrev>
++++

Uses an alert ID (`alert id`) to retrieve the case IDs of any cases the alert is attached to.

TIP: The case ID is identical to the case's saved object ID.

=== Request

`GET <kibana host>:<port>/api/cases/alerts/<alert_id>`

=== Path parameters

`alert_id`::
(Required, string) The alert identifier.

=== Query parameters

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`owner` |String or String[] |A filter to limit the retrieved case IDs to a specific set of applications. If you omit this parameter, the response will contain every case ID that the user has `read` access to. |No

|==============================================

=== Response code

`200`::
   Indicates a successful call.

=== Example

Return case IDs with the alert ID `293f1bc0-74f6-11ea-b83a-553aecdb28b6` attached to them:

[source,sh]
--------------------------------------------------
GET api/cases/alerts/293f1bc0-74f6-11ea-b83a-553aecdb28b6
--------------------------------------------------
// KIBANA

The API returns a JSON array containing any case IDs associated with the specified alert. Case titles are also retrieved. For example:

[source,json]
--------------------------------------------------
[
    {
        "id": "8af6ac20-74f6-11ea-b83a-553aecdb28b6",
        "title": "Test 1"
    },
    {
        "id": "a18b38a0-71b0-11ea-a0b2-c51ea50a58e2",
        "title": "Test 2"
    }
]
--------------------------------------------------
