[[release-notes]]
= {kib} Release Notes

[partintro]
--
// To add a release, copy and paste the template text
// and add a link to the new section. Note that release subheads must
// be floated and sections cannot be empty.

// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/kibana/issues/
:pull: https://github.com/elastic/kibana/pull/

This section summarizes the changes in each release.

* <<release-notes-7.0.0>>

--

////
// To add a release, copy and paste the following text,  uncomment the relevant
// sections, and add a link to the new section in the list of releases at the
// top of the page. Note that release subheads must be floated and sections
// cannot be empty.
// TEMPLATE:

// [[release-notes-n.n.n]]
// == {kib} n.n.n

//[float]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

//[float]
//=== Bug Fixes

//[float]
//=== Regressions

//[float]
//=== Known Issues
////

[[release-notes-6.2.4]]
== {kib} 6.2.4

//[float]
//[[breaking-6.2.4]]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

[float]
=== Enhancements

Visualization::
* Upgraded Vega libraries:  `vega-lib` to 3.2.1 and `vega-lite` to 2.3.1 {pull}17314[#17314]

[float]
=== Bug Fixes

Management::
* Added better support for discarding results of older queries {pull}17148[#17148]

Platform::
* Fixed an issue with the numeric formatter to handle small exponential numbers {pull}17508[#17508]
* Fixed deprecation logging warnings {pull}17439[#17439]

Visualization::
* Fixed map zoom settings {pull}17367[#17367]
* Enabled Option change to show on map {pull}17405[#17405]
* Added support for percentiles and percentile ranks to metrics visualizations {pull}17243[#17243]

//[float]
//=== Regressions

//[float]
//=== Known Issues

[[release-notes-6.2.3]]
== {kib} 6.2.3

//[float]
//[[breaking-6.2.3]]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

//[float]
//=== Bug Fixes

//[float]
//=== Regressions

[float]
=== Known Issues

{pull}17139[#17139] Cross cluster search index pattern won't go to next step.


[[release-notes-6.2.2]]
== {kib} 6.2.2

//[float]
//[[breaking-6.2.2]]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

[float]
=== Bug Fixes

Design::
* [Fixes #4475] Removing flex-basis: 0 to make items size properly in IE11 {pull}16557[#16557]

Management::
* [Fixes #16304] [Management] Prevent react warnings in index pattern creation {pull}16520[#16520]

Platform::
* Destroying socket when we get a clientError {pull}16700[#16700]

//[float]
//=== Regressions

//[float]
//=== Known Issues

[[release-notes-6.2.1]]
== {kib} 6.2.1

There were no changes for this release.

//[float]
//[[breaking-6.2.1]]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

//[float]
//=== Bug Fixes

//[float]
//=== Regressions

//[float]
//=== Known Issues

[[release-notes-6.2.0]]
== {kib} 6.2.0

//[float]
//[[breaking-6.2.4]]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

[float]
=== Enhancements

Discover::
* [Fixes #15642] Introduce simple kibana query language {pull}15646[#15646]

Management::
* [Fixes #9228, #8983] add support for number format internationalization {pull}14019[#14019]
* [Fixes #15922] [Management] Index pattern step in React! {pull}15936[#15936]
* Advanced Settings - Image Input {pull}15342[#15342]

Operations::
* Use auto_expand_replicas to stay green on 1 node clusters {pull}15694[#15694]
* Feat: Add config provider to disable state management {pull}15275[#15275]
* [optimizer] More aggressive chunking of common/vendor code {pull}15907[#15907]
  - Improved the build optimize time by more aggressively chunking common code, resulting in the removal of duplicate code. This drastically cuts the build and plugin install time and overall bundle asset size.
* [Fixes #14813] [ui/bundles][optimizer] only use caches when in dev mode {pull}15780[#15780]
* [optimizer] run webpack compilation ASAP (no more laziness) {pull}15795[#15795]

Platform::
* [Fixes #6520] [optimizer] allow http caching for bundles {pull}15880[#15880]
* Make it possible to disable CSRF check for the specified list of paths. {pull}13904[#13904]

Sharing::
* [Fixes #2758] Add advanced setting to control quick ranges {pull}15975[#15975]
* [input controls] Horizontal layout {pull}14918[#14918]
* Kibana Home page - phase two {pull}14749[#14749]
* Add &quot;use time filter&quot; option to input controls {pull}15852[#15852]

Visualization::
* [Fixes #13992] Grab the default index pattern and use it in TSVB {pull}14739[#14739]
  - TSVB now uses Kibana's default index pattern by default.
* [TSVB] Add params._interval to mathjs {pull}14944[#14944]
  - Make the bucket interval available as a parameter.
* [Fixes #13781] [timelion] allow sum, subtract, multiply, divide functions to accept seriesList with multiple series {pull}14891[#14891]
* [Fixes #8953] Add Timelion percentiles aggregation support (#8953) {pull}15154[#15154]
* [Fixes #9845] [timelion] highlight series on legend mouseover {pull}15229[#15229]
* add time to visualization status {pull}15856[#15856]
* few enhancements to default sidebar editor {pull}15619[#15619]
  - Its now possible to resize the sidebar editor and auto apply is possible in markdown visualization.
* [Fixes #1961] other and missing bucket support for terms agg {pull}15525[#15525]
  - 'other' and 'missing' bucket for the terms aggregation resolves #1961
* [Fixes #15146] Refactor and improve Visualize Loader {pull}15157[#15157]
  - Do not use the &lt;visualize&gt; directive anymore to embed a visualization. Use the Visualize Loader instead.
* [Fixes #15153] Use visualize loader for dashboards {pull}15444[#15444]
* Refactor rendering events {pull}15895[#15895]
* Migrating vega_vis from plugin {pull}15014[#15014]


[float]
=== Bug Fixes

Discover::
* display NOT when new filter is negated {pull}15865[#15865]
* [Fixes #15364] Truncate long names in the discover index pattern selection {pull}15510[#15510]
* Add missing discover labels {pull}16030[#16030]

Management::
* [Fixes #16098] [Management] Allow wildcard anywhere in the search query {pull}16109[#16109]
* [Fixes #16192] [Management] Update pager with new props in Index Pattern Creation {pull}16195[#16195]
* [Fixes #15922] Hide caret when indices has no time fields, remove indices object containing unused string {pull}16412[#16412]

Sharing::
* [Fixes #16307] link to dashboards by id instead of title {pull}16319[#16319]

Visualization::
* [Fixes #16349] Fix issue with disabled lab mode {pull}16351[#16351]
* [TSVB] Changing the behaivor of getLastValue to get the actual last value {pull}14919[#14919]
* [TSVB] Stacked series should not contain null values {pull}14923[#14923]
* [Fixes #15273] disable input control when field contains no values in index pattern {pull}15317[#15317]
* Set list-style-type for list items in markdown-body {pull}15827[#15827]
* Visualization render status - pass correct parameters to resize check {pull}15855[#15855]
* fixes angular vis type so it correctly propagates events up to visualize {pull}15629[#15629]
* [Fixes #15427] fixing dot ratio slider {pull}15860[#15860]
  - dot size slider for line chart works again
* fixing log scale error {pull}15984[#15984]
  - log scale now works with empty buckets
* [Fixes #15114] fixing boolean filters {pull}15927[#15927]
* [Fixes #15931, #15656] check if data hash changed instead of stringifying {pull}15988[#15988]
  - performance of visualization rendering is improved
* Remove SVG element styling rules {pull}15906[#15906]
* [Fixes #15553] Fix bug where negative time offsets in visual builder will shift x-axis range {pull}15554[#15554]
* [6.x] Fix maps for reporting (#15272) {pull}15357[#15357]
* Sharing - exposing Dashboard and Visualize title and type {pull}14946[#14946]
* [Fixes #14730] pass bucket size as _interval param to calculation metric script {pull}14731[#14731]
* [Fixes #15672, #14353] Revert Resize and FlotChart components to 6.0 {pull}15717[#15717]
* [Fixes #15501] [TSVB] Fixes #15501 - Change xaxis formatter to honor dateFormat:tz {pull}15512[#15512]
* [TSVB] Make form font-sizes consistent (after EUI upgrade) {pull}15909[#15909]
* Remove MathJS Feature {pull}15652[#15652]
* [TSVB] Add checks for scaledDataFormat and dateFormat in xaxisFormatter {pull}15997[#15997]
* [TSVB] Fix typo is filter ratio path for table visualization {pull}16052[#16052]
* [Fixes #14888] [timelion] provide argument suggestions when argument name not provided {pull}15081[#15081]
* [Fixes #15594] fixes pie chart size to normal if labels are not applied {pull}15641[#15641]
* [Fixes #15818] fixing collapsible side bar editor {pull}15826[#15826]
* [Fixes #15703] refactoring vis uiState {pull}15709[#15709]
* [Fixes #15673] fixes table padding on dashboard {pull}15862[#15862]
* [Fixes #15778] fixing tag cloud and region map click handler {pull}15861[#15861]
* fixes renderComplete in angular vis type {pull}16150[#16150]
* [Fixes #16217] fixing axis title position for firefox {pull}16278[#16278]
* [Fixes #13822] visualize editor should not show if embed is set to true in url {pull}16310[#16310]
* [Fixes #16083] configure Kibana with production endpoint for EMSv3 {pull}16108[#16108]
* [Fixes #13813] Use a width range instead of a fixed width for visualize legends {pull}13818[#13818]
* should always set base layer {pull}16213[#16213]
* Extract lab HTML on dashboard into own file {pull}15546[#15546]
* Remove implementsRenderComplete property {pull}15579[#15579]
* [Fixes #15255] Set uiState to Vis from visualization {pull}15549[#15549]
* [Fixes #15618] Fix broken initial uiState set {pull}15630[#15630]
* [Fixes #15742] Only apply forced max mode when panel is shown {pull}15752[#15752]
* Fix JSON hint styling and accessibility {pull}15890[#15890]
* [Fixes #15712] Fix broken editor styles {pull}15735[#15735]
* [Fixes #15713] Use euiCallOut for experimental banner {pull}15989[#15989]
* Fix some styling issues {pull}16023[#16023]
* Listen to resize events in &lt;visualize&gt; {pull}16048[#16048]
* [Fixes #16216] Prevent rendering into 0 size containers {pull}16287[#16287]
* [Fixes #14331] Add topojson support / EMS v3 support {pull}15361[#15361]

//[float]
//=== Regressions

//[float]
//=== Known Issues

[[release-notes-6.1.3]]
== {kib} 6.1.3

//[float]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

[float]
=== Bug Fixes

Visualization::
* Use textContent and jQuery to set label and title {pull}16178[#16178]

//[float]
//=== Regressions

//[float]
//=== Known Issues

[[release-notes-6.1.2]]
== {kib} 6.1.2

//[float]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

[float]
=== Security Issues

* Kibana versions before 6.1.2 and 5.6.6 but after 5.1.1 had a cross-site scripting (XSS) vulnerability via the colored fields formatter that could allow an attacker to obtain sensitive information from or perform destructive actions on behalf of other Kibana users. CVE ID: CVE-2018-3818

Users should upgrade to Kibana version 6.1.2 or 5.6.6. There are no known workarounds for this issue.

[float]
=== Enhancements

Dev Tools::
* [Fixes #15786] [Console] Adding autocomplete rules for composite agg {pull}15787[#15787]

[float]
=== Bug Fixes

Visualization::
* [Fixes #15843] Fix broken loader in 6.1 {pull}15885[#15885]
* [Fixes #15594] fixes pie chart size to normal if labels are not applied {pull}15641[#15641]

Platform::
* Update color field formatter {pull}15837[#15837]

//[float]
//=== Regressions

//[float]
//=== Known Issues

[[release-notes-6.1.1]]
== {kib} 6.1.1

//[float]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

[float]
=== Bug Fixes

Management::
* Allow pasting into index pattern field using keyboard shortcut {pull}15500[#15500]
* Typing a CCS pattern into the index pattern field no longer triggers an error {pull}15372[#15372]

Operations::
* Bump node.js version to 6.12.2 {pull}15612[#15612]
* Kibana indices are no longer flagged as out-of-date just because they include `_default_` {pull}15432[#15432]

Visualizations::
* Disable math aggregation in Time Series Visual Builder {pull}15653[#15653]
* Bucket paths for overall aggregations now use syntax compatible with Elasticsearch 6+ {pull}15322[#15322]

//[float]
//=== Regressions

//[float]
//=== Known Issues

[[release-notes-6.1.0]]
== {kib} 6.1.0

//[float]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

[float]
=== Enhancements

Design::
* [Fixes #12889] Make saved-object-finder and paginated-selectable-list accessible {pull}13834[#13834]
* [Fixes #12901] [UI Framework] Add KuiCodeEditor as react-ace replacement/wrapper {pull}14026[#14026]
* [UI Framework] KuiGalleryItem automatically becomes link or button {pull}14240[#14240]

Dev Tools::
* [Fixes #11522] Improve Dev Tools accessibility {pull}13496[#13496]
  - Console no longer traps keyboard focus. You can quit editing with Escape.

Discover::
* [Fixes #12633, #12641] Improve accessibility of the discover app {pull}13498[#13498]
* [Fixes #14456] [Accessibility] Improve filter bar accessibility {pull}14474[#14474]

Management::
* [Fixes #12867] &quot;Create index pattern&quot; wizard.  {pull}13454[#13454]
  - Introducing a new wizard to create index patterns that makes index discovery and matching much easier than before.
* [Fixes #12668] add an option for url types so that it can be opened in current tab (master branch) {pull}13209[#13209]
* [Fixes #12869, #12873, #13803] Improve Management section accessibility {pull}14243[#14243]
* Add rel=&quot;noopener noreferrer&quot; to external links {pull}14440[#14440]

Operations::
* [Fixes #11091] Adds keystore for storing settings {pull}14714[#14714]
* [eslint-config-kibana] Add AirBnB linting rules for React best practices. Bump to v0.10.0. {pull}13259[#13259]
* Add updated_at timestamp to saved objects {pull}13503[#13503]
* [Fixes #14312] [build] Clean examples from node modules {pull}14587[#14587]
* [SavedObjects] use constructor options {pull}14200[#14200]
* [savedObjects] wait for Kibana index on every write {pull}14202[#14202]
* [es/clusters] improve cleanup {pull}14188[#14188]
* Upgrade to webpack 3 {pull}14315[#14315]
* Upgrade to eslint 4 {pull}14862[#14862]
* Proxy support for plugin installer {pull}12753[#12753]
  - Kibana now respects the http_proxy, https_proxy and no_proxy environment variables to download plugins via a proxy.
* [Fixes #13937] Make console history keyboard accessible {pull}13946[#13946]

Platform::
* [Fixes #8499] [server/logging] Allow opting out of UTC {pull}14705[#14705]
* Improve performance of sort_prefix_first for large arrays {pull}14974[#14974]

Sharing::
* Add a feature for custom panel titles {pull}14831[#14831]
  - Introduces the ability to specify custom titles, or remove the title entirely, for individual dashboard panels.  Just hit the reset link to restore the title to it's original value.
* Input Control visualization {pull}13314[#13314]
* Kibana Home page - phase one {pull}14673[#14673]
* only show expand toggle, in view mode, on hover {pull}14706[#14706]
* [Fixes #13948] Add new &quot;use margins&quot; option to add separation between panels {pull}14708[#14708]
* Add new title query param to dashboard listing page {pull}14760[#14760]
* [Fixes #12563] Hide all panel titles option at the dashboard level {pull}15006[#15006]

Visualization::
* [Fixes #1702] pie chart labels {pull}12174[#12174]
  - pie charts can now have labels on them to increase readability
* [Fixes #13519, #13103, #13968] Improve Region Maps for use without network connection {pull}15056[#15056]
  - Improve the use of Region Maps for deployment in environments without internet access. Similar to the Coordinate Map visualization, the Region map can now use a WMS-service as a base-layer. Admins can now also setup Kibana to opt-out of connection to the Elastic Maps Service. Users can now opt-out of having the visualization display warnings.
* Introduce lab mode for visualizations {pull}15050[#15050]
  - Newly introduced visualizations can now be part of labs-mode. Visualizations in labs-mode introduce new more cutting-edge functionality and can be subject to change across minor releases.  Labs-mode can be turned off in the advanced settings. Labs-visualization will then no longer be available to the user. The Time Series Visual Builder is not part of labs-mode, it continues to be an experimental feature. The input controls are the first to be flagged as a lab visualization.
* reverts metric visualization {pull}14052[#14052]
  - The metric visualization now no longer reuses the rendering code of the gauge and goal visualizations. This improves consistency of positioning of the metric on Dashboards.
* [TSVB] Adding the ability to sort terms split by terms and change order {pull}14213[#14213]
* Math Aggregation to support Sibling Aggs for TSVB {pull}13681[#13681]
* [TSVB] Add support for Math Aggregation to tables {pull}14553[#14553]
  - This PR adds support for the Math aggregation to the new TSVB table visualization. This wasn't possible at the time of the PR because both features were separated. This also adds support for the drop last bucket feature.
* [TSVB] Series Filter {pull}14696[#14696]
  - This PR adds the series filter feature allowing the user to create a filter per series. This allows users to user to have a group by terms along with a filter for each series.
* [Fixes #13992] Grab the default index pattern and use it in TSVB {pull}14739[#14739]
  - TSVB now uses Kibana's default index pattern by default.
* [TSVB] Add params._interval to mathjs {pull}14944[#14944]
  - Make the bucket interval available as a parameter.
* Upgrade kibana to leaflet 1.x {pull}12367[#12367]
* [Fixes #1385] relative date field formatter {pull}13921[#13921]
* Allow visualizations to specify open editor tab  {pull}13977[#13977]
* Show the x-axis (time) value in legend when hovering over a Timelion graph {pull}14627[#14627]
  - Hovering over a Timelion  graph now shows the corresponding x-axis value in the legend.
* Timelion typeahead for argument names {pull}14657[#14657]
* [Fixes #9022] Timelion query language support for scripted fields {pull}14700[#14700]
* Timelion typeahead for argument values {pull}14801[#14801]
* add API to embed visualizations {pull}14292[#14292]
  - visualize loader helps with inserting visualizations into DOM elements
* [Fixes #11533] Improve timelion accessibility {pull}13531[#13531]
* [Fixes #11858] Allow reordering aggregation priority by keyboard {pull}13635[#13635]
* [Fixes #12902, #12903] Improve time series visual builder accessibility {pull}13817[#13817]
* [Fixes #11843] [Accessibility] Improve visualization legends accessibility {pull}14505[#14505]
  - Improve the keyboard accessibility of visualization legends.
* [Fixes #12905] [Accessibility] Refactor font slider for accessibility {pull}14817[#14817]
* Remove ready:vis and application.load event {pull}14988[#14988]
  - Visualizations no longer send a ready:vis event to the $rootScope once they initialized. Applications don't need to emit an application.load event anymore.

[float]
=== Bug Fixes

Design::
* [Fixes #12247] [Accessibility] Make table pagination controls keyboard-accessible.  {pull}13541[#13541]
* [Fixes #12482] [Accessibility] Give kuiTables keyboard-accessible column headers  {pull}13586[#13586]
* [UI Framework] Reset Chrome's native styling for button border-radius {pull}14758[#14758]
* [UI Framework] Fix spacing bug with LocalTabs. {pull}14772[#14772]

Dev Tools::
* [Fixes #14586] [console] Remove cluster/_nodes/stats {pull}14757[#14757]
* [Fixes #10841, #10840, #10071, #8930, #9651, #8790] [console] assorted autocomplete fixes {pull}14770[#14770]

Management::
* [Fixes #12612] Create keyboard mode for ui-ace editor {pull}13339[#13339]
  - Our code editor in several places won't trap keyboard focus anymore, by using the Tab key. When navigating by keyboard, you first need to Enter editing mode in the code editor and you can leave it by pressing Escape.

Operations::
* Removes webpack-directory-name-as-main dependency {pull}13584[#13584]

Platform::
* [Fixes #15078] Courier - $state in searchSource {pull}15166[#15166]

Sharing::
* Refine use of aria-label in Dashboard panel and top nav, Discover, and Management 'Edit index pattern' UI. {pull}14341[#14341]
* [Fixes #11532] [11532] Improve local nav accessibility  {pull}14365[#14365]
* Fix bug with Dashboard breadcrumb alignment. {pull}13580[#13580]
* [Fixes #13421] Dashboard dark-theme fixes {pull}13690[#13690]
* Set timeout and terminate_after parameters when fetching terms for Input Controls {pull}14977[#14977]
* [Fixes #13458] Fix out of memory crash on auto refreshing dashboards {pull}13871[#13871]
* [Fixes #9523] Fix issue where saved searches are not updated {pull}14452[#14452]
  - There has been a long standing issue where if you add a saved search to a dashboard, then go edit and save that saved search, the updates are not propagated to the dashboard.  The only way, previously, to get the new changes was to remove and re-add the search from your dashboard. With this fix, that is no longer necessary. However, there is one situation when your saved search will stop updating and that is when someone has made and saved local edits to the saved search on the dashboard.  For example, if you remove a column from a saved search in a dashboard panel, then save the dashboard, that search will always show that column set, even if columns are added or removed to the underlying saved search. We did it this way to still allow users to override the configuration at the dashboard level.

Visualization::
* Visualization resizeInit {pull}15321[#15321]
* [Fixes #14344] Remove aria-hidden=&quot;true&quot; from TSVB tabs and agg component to make their content screen-reader accessible. {pull}14345[#14345]
* [TSVB] Remove console.log from Resize PR {pull}14555[#14555]
* [TSVB] Fixes #14124 - Removes the 1w label from interval pattern {pull}14577[#14577]
* [TSVB] Change term sorting to match Kibana Core {pull}14679[#14679]
* [TSVB] Stacked series should not contain null values {pull}14923[#14923]
* fix issue of duplicate TSVB flot chart creation {pull}14626[#14626]
* Fix spatial filters when Kuery is in use {pull}14158[#14158]
* [6.x] update spy table headers when columns update {pull}13224[#13224]
* [Fixes #2908] Scale histogram aggregation interval to avoid crashing browser {pull}14157[#14157]
* [Fixes #12545] [timelion] trim number of colors when there are more colors than gradient stops {pull}14906[#14906]



//[float]
//=== Regressions

//[float]
//=== Known Issues

// [[release-notes-6.0.1]]
// == {kib} 6.0.1

//[float]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

//[float]
//=== Bug Fixes

//[float]
//=== Regressions

//[float]
//=== Known Issues

// [[release-notes-6.0.0]]
// == {kib} 6.0.0

//[float]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

//[float]
//=== Bug Fixes

//[float]
//=== Regressions

//[float]
//=== Known Issues

// [[release-notes-6.0.0-rc2]]
// == {kib} 6.0.0-rc2

//[float]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

//[float]
//=== Bug Fixes

//[float]
//=== Regressions

//[float]
//=== Known Issues

// [[release-notes-6.0.0-rc1]]
// == {kib} 6.0.0-rc1

//[float]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

//[float]
//=== Bug Fixes

//[float]
//=== Regressions

//[float]
//=== Known Issues

// [[release-notes-6.0.0-beta2]]
// == {kib} 6.0.0-beta2

//[float]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

//[float]
//=== Bug Fixes

//[float]
//=== Regressions

//[float]
//=== Known Issues

// [[release-notes-6.0.0-beta1]]
// == {kib} 6.0.0-beta1

//[float]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

//[float]
//=== Bug Fixes

//[float]
//=== Regressions

//[float]
//=== Known Issues

// [[release-notes-6.0.0-alpha2]]
// == {kib} 6.0.0-alpha2

//[float]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

//[float]
//=== Bug Fixes

//[float]
//=== Regressions

//[float]
//=== Known Issues

// [[release-notes-6.0.0-alpha1]]
// == {kib} 6.0.0-alpha1

//[float]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

//[float]
//=== Bug Fixes

//[float]
//=== Regressions

//[float]
//=== Known Issues